name: Deployment 2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependences
        run: npm i
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependences
        run: npm i
      - name: Test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code
        run: actions/checkout@v3
      - name: Install dependences
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Deploy
        run: npm run build